### ISSUE TITLE
Map/Theme keyboarding (Accessibility)

### ISSUE THREAD

**Issue by jmulliken** [statsmaths/layered-lives#4]
Can map/themes be made more accessible y adding keyboard functionality? Currently can't select points or move map without mouse. Once points are open, cannot close without mouse.

**Comment by statsmaths** [comment]
I made some good progress on these. See edits in 105b5223a4c606c5db412863247ab0a98de3bf0c. Also just pushed a compiled version with the changes to GitHub pages.

The map should be zoomable with the plus and minus keys and pannable with the arrow keys *assuming you are focused on the map*. Note though that the map will push you back to the American South if you get too far away from the points.

The close button on the list of interviews in a location is now focusable and works with the enter key. Same goes for the interviews in the map view, as well as all of the topics and interviews in the topic model explorer.

I tested these in Firefox and Safari on a mac, though note that Safari requires you go into the advanced settings and turn on tab navigation (not sure why).

**Comment by statsmaths** [comment]
The one thing I could not get to work is making the points on the map selectable from the keyboard. Those are elements within an SVG elements; I couldn't figure out how to make them selectable. The trick that worked everywhere else (wrapping them in a <button>) is not possible inside an SVG.

**Comment by jmulliken** [comment]
This is already much better, and I appreciate your work!
